# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 38d0d19222236bd15377aa557c5f9341721a4c59ffc9a839c5adf3e25005d65b6e1d932ce9a5e6fcb8d904ae1ff93f6a44a2fa30de74a62ffb1f4bebd0112e63

test:
  secret_key_base: f47521d778b356505c3a7a5d757872975886a68b403740010536444833a94d27dc1b40eb7f1cdd2385fe404f4a7745addff46b77dbaf6f489477365d00348947

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
